<script setup>
import { nextTick, onMounted, ref } from 'vue'

// 'loading' until the first response, then 'ready' or 'unavailable'.
const state = ref('loading')
const plugins = ref([])

const expanded = ref(new Set())
const overflowing = ref(new Set())
const descriptionEls = new Map()

function registerDescription(name, el) {
  if (el === null) {
    descriptionEls.delete(name)
  } else {
    descriptionEls.set(name, el)
  }
}

function toggle(name) {
  const next = new Set(expanded.value)
  next.has(name) ? next.delete(name) : next.add(name)
  expanded.value = next
}

// A control that expands nothing is worse than no control, so it only appears
// on the cards whose text is actually taller than the clamp allows.
function measure() {
  const next = new Set()
  for (const [name, el] of descriptionEls) {
    if (el.scrollHeight > el.clientHeight + 1) {
      next.add(name)
    }
  }
  overflowing.value = next
}

onMounted(async () => {
  // Bounds the request so a stalled connection between the browser and the
  // server cannot leave the page saying "Loading the catalogue" forever. The
  // server's own upstream timeout does not help here: it only bounds the call
  // to store-api, not this fetch.
  const controller = new AbortController()
  const timeoutId = setTimeout(() => controller.abort(), 5000)

  try {
    const response = await fetch('/api/plugins', { signal: controller.signal })
    if (!response.ok) {
      state.value = 'unavailable'
      return
    }
    const body = await response.json()
    plugins.value = body.plugins ?? []
    // available:false means the server could not reach store-api and had
    // nothing cached. Say so rather than rendering an empty grid, which would
    // read as "there are no plugins".
    state.value = body.available ? 'ready' : 'unavailable'
  } catch {
    // Covers a network failure and the timeout above firing the abort, since
    // both should read the same way to a visitor: the catalogue is unreachable.
    state.value = 'unavailable'
  } finally {
    clearTimeout(timeoutId)
    // Runs for every outcome above, not just the happy path: an empty list or
    // an unavailable catalogue still needs the DOM update from the state
    // change to flush before measure() looks for cards, and calling it
    // unconditionally here means no branch can forget to.
    await nextTick()
    measure()
  }
})
</script>

<template>
  <p v-if="state === 'loading'" class="gl3-plugins-note" role="status">Loading the catalogue.</p>

  <p v-else-if="state === 'unavailable'" class="gl3-plugins-note" role="status">
    The plugin catalogue is not reachable right now. Everything else on this site still
    works, and the list will come back on its own.
  </p>

  <p v-else-if="plugins.length === 0" class="gl3-plugins-note" role="status">
    No plugins are published yet.
  </p>

  <ul v-else class="gl3-plugins">
    <li v-for="plugin in plugins" :key="plugin.name">
      <article class="gl3-plugin">
        <header>
          <!-- target="_self" is load bearing. VitePress intercepts every
               same origin link ending in .html and resolves it against its own
               route table, which these server rendered pages are not in, so a
               plain link renders VitePress's 404 without ever reaching the
               server. Its router skips interception only for a link carrying
               "download" or "target", and it does not look at rel, so
               rel="external" would not work here. "_self" keeps the navigation
               in the same tab while forcing a real request. -->
          <h3><a :href="plugin.href" target="_self">{{ plugin.name }}</a></h3>
          <span :class="['gl3-tag', plugin.paid ? 'is-paid' : 'is-free']">
            {{ plugin.paid ? 'Premium' : 'Free' }}
          </span>
        </header>

        <div v-if="plugin.descriptionHtml" class="gl3-plugin-description">
          <!-- Already sanitised by the server, which is the only place package
               markdown becomes HTML. Nothing here re-parses it. -->
          <p
            :class="{ 'is-clamped': !expanded.has(plugin.name) }"
            :ref="(el) => registerDescription(plugin.name, el)"
            v-html="plugin.descriptionHtml"
          ></p>
          <button
            v-if="overflowing.has(plugin.name)"
            type="button"
            class="gl3-plugin-more"
            :aria-expanded="expanded.has(plugin.name)"
            @click="toggle(plugin.name)"
          >
            {{ expanded.has(plugin.name) ? 'Show less' : 'Show more' }}
          </button>
        </div>

        <footer>
          <code>{{ plugin.install }}</code>
          <span class="gl3-version">v{{ plugin.version }}</span>
        </footer>
      </article>
    </li>
  </ul>

  <!-- The grid needs a request the build cannot make, so this is the only
       listing of the plugin pages that can be linked from here: the sitemap is
       generated by the same server that serves those pages. -->
  <noscript>
    <p class="gl3-plugins-note">
      This page needs JavaScript to load the plugin catalogue. Every plugin has its own
      page, and <a href="/sitemap.xml">the sitemap</a> lists them all. You can also browse
      published packages under the
      <a href="https://www.npmjs.com/search?q=%40gl3">@gl3 scope on npm</a> or see
      <a href="https://docs.gl3.dev">docs.gl3.dev</a>.
    </p>
  </noscript>
</template>
